id: P010778
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:24:06.760979
source_metadata:
  id: bdr:W8LS16572
  title: ཡོན་ཏན་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འབྲུ་འགྲེལ།
  author: ''
  volumes:
    4fed28a6be384333b21c4890fc13d7e4:
      image_group_id: I8LS16605
      title: ''
      volume_number: 1
      total_pages: 498
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
