id: I363C3898
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:31:40+00:00'
last_modified: '2022-06-08T17:27:34.659698+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16572
  title: ཡོན་ཏན་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འབྲུ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DFD5:
      image_group_id: I8LS16605
      title: ''
      total_pages: 498
      order: 1
      base_file: DFD5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
